import type { NextPage } from "next";
import Head from "next/head";
import { Posts } from "../components/Blog/Posts";
import { Profile } from "../components/Profile/Profile";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className="name-title">
					<h1>Nicolás Vazquez</h1>
					<p>Desarrollador de Software</p>
				</div>
				<hr />

				<section>
					<Profile />
					<Posts />
				</section>
			</main>

			{/* @ts-ignore */}
			<style jsx>{
				/*css*/ `
					h1 {
						margin-bottom: 1rem;
					}
					.name-title {
						text-align: center;
						margin-bottom: 2rem;
					}
					@media (min-width: 768px) {
						section {
							display: flex;
							justify-content: space-evenly;
							align-items: start;
							min-width: 70%;
						}
					}
				`
			}</style>
		</div>
	);
};

export default Home;
